# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "tomcat" do |tomcat|
    tomcat.vm.network :hostonly, "192.168.1.33"
    tomcat.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "tomcat.pp"
    end
  end
end